"""init

Revision ID: 380fcd5ef99d
Revises: 
Create Date: 2023-03-08 20:16:47.641134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380fcd5ef99d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
